version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  db2:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appseed
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appseed-flask  
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
    env_file:
      - .env
    # networks:
    #   - "backend"       
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
      - db2
   
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  postgres_data2: 